export const NOTES = [
  "C",
  "C# / Db",
  "D",
  "D# / Eb",
  "E",
  "F",
  "F# / Gb",
  "G",
  "G# / Ab",
  "A",
  "A# / Bb",
  "B",
];
export const QUALITIES = [
  {
    label: "Majeurs",
    options: [
      { value: "", text: "Majeur" },
      { value: "6", text: "Majeur 6" },
      { value: "maj7", text: "Majeur 7" },
      { value: "add9", text: "Add 9" },
      { value: "6/9", text: "Majeur 6/9" },
      { value: "maj9", text: "Majeur 9" },
      { value: "maj13", text: "Majeur 13" },
      { value: "maj7#5", text: "Majeur 7#5" },
    ],
  },
  {
    label: "Mineurs",
    options: [
      { value: "m", text: "Mineur" },
      { value: "m6", text: "Mineur 6" },
      { value: "m7", text: "Mineur 7" },
      { value: "m(maj7)", text: "m(maj7)" },
      { value: "m(add9)", text: "m(add9)" },
      { value: "m9", text: "Mineur 9" },
      { value: "m11", text: "Mineur 11" },
      { value: "m13", text: "Mineur 13" },
    ],
  },
  {
    label: "Dominante",
    options: [
      { value: "7", text: "7" },
      { value: "9", text: "9" },
      { value: "11", text: "11" },
      { value: "13", text: "13" },
      { value: "7b5", text: "7♭5" },
      { value: "7#5", text: "7♯5" },
      { value: "7b9", text: "7♭9" },
      { value: "7#9", text: "7♯9" },
      { value: "7#11", text: "7♯11" },
    ],
  },
  {
    label: "Altérés",
    options: [
      { value: "7b9b5", text: "7♭9♭5" },
      { value: "7b9#5", text: "7♭9♯5" },
      { value: "7#9b5", text: "7♯9♭5" },
      { value: "7#9#5", text: "7♯9♯5" },
      { value: "7b9#9", text: "7♭9♯9" },
      { value: "7b9#11", text: "7♭9♯11" },
      { value: "7#9#11", text: "7♯9♯11" },
      { value: "7b9b13", text: "7♭9♭13" },
      { value: "7#9b13", text: "7♯9♭13" },
    ],
  },
  {
    label: "Suspendus",
    options: [
      { value: "sus2", text: "sus2" },
      { value: "sus4", text: "sus4" },
      { value: "7sus2", text: "7sus2" },
      { value: "7sus4", text: "7sus4" },
      { value: "9sus4", text: "9sus4" },
    ],
  },
  {
    label: "Diminués",
    options: [
      { value: "dim", text: "Diminué" },
      { value: "m7b5", text: "m7b5" },
      { value: "dim7", text: "Diminué 7" },
    ],
  },
  { label: "Augmentés", options: [{ value: "aug", text: "Augmenté" }] },
  { label: "Autres", options: [{ value: "5", text: "Power Chord" }] },
];
